/**:
  ros__parameters:
    costmap_converter_plugin: "d2_costmap_converter::CostmapToPolygonsDBSMCCH"
    converter_rate: 5.0
    costmap_lethal_threshold: 99
    submap_size_x: 20.0
    submap_size_y: 5.0
    target_frame: "map"
    submap_front: 8.0
    submap_rear: 3.0
    submap_side: 3.0
    pointcloud_min_distance: 0.5
    pointcloud_max_distance: 8.0
    pointcloud_min_height: -0.7
    pointcloud_max_height: 1.0
    voxel_leaf_size: 0.1